language: python

python:
- &latest_py3 3.8
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7

env:
- TOXENV=python

jobs:
  fast_finish: True
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    before_script: skip
    env:
    - FLIT_USERNAME=__token__
    # FLIT_PASSWORD
    - secure: "DTuasBqocwWziNCZ9oNdHdThD5b+Kbfv+4Loi2sW6zdZZnanHRantUg9jMQHEWS8SwFgvjsUlIjcjgALGeDV3Ya+ACm0KcsCiGCHYcG7XtYjKmIfXhQ1c6/YTAMi0z/aXjmXttFjwNySGQ6eXSrqMGs3m44zuVV3BSCpW9jLezmGiXltxKfxUCePxMrpFr66CKD3/Js3xQxUYp5MP50qz3FTASURSGivw2cEeuMJy+PtHahhqAjpq13SPMZuMshZGy2t3uP3qf91edMqxZ/sVf803fBbqZL+MEOmT1mTx5ZTZBXdoCUKWydfEbF5jclpvdSc9SNa3rX3sGh0yhcHPQUdyO4BJuERxhyqs7FWs8hJBp40bDkaX/QDXHQiCidO6Ayrm7c75aA+OkxU8suxFDBsF4gRzqkejL3E8wz26Ye7IfEwoKYbUw0S9aHzwwmJZWNgM0QhdP7nDbUVIGYkjPmgNc8HHmkMyPu0WbwiwatDv16pR2Mvk2fjhuP5McUeHmrI57UGyVnxq8JbUjD11G0RW4XqWoqybWSYhHTHFORr2OjodJsprUN+dFzKyVmwPE60yr3Ve0H4roM/W98wh4S7EqRn4rJt1NqC8q8ZRTe2D0bb5ancPYCe+lQcvgO2YDNzDh8kucGON9fEgSFZ9mVG0Fa1UG3EvXJ3K7FjbyA="
    - TOX_TESTENV_PASSENV="FLIT_USERNAME FLIT_PASSWORD"
    - TOXENV=release
    script: tox

cache: pip

install:
- pip install tox tox-venv

script: tox
